# Descomentar la siguiente línea para definir una plataforma global para tu proyecto
platform :ios, '12.0'

# Ignorar el bloqueo de versiones de CocoaPods
install! 'cocoapods', :disable_input_output_paths => true

# Descomentar esta línea si tienes problemas con dependencias o compilaciones de CocoaPods
# ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'))
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} no se encontró. Ejecute `flutter pub get` en el proyecto Flutter primero."
  end
  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT no se encontró en #{generated_xcode_build_settings_path}. Ejecute `flutter pub get` en el proyecto Flutter primero."
end

flutter_application_path = File.join(__dir__, '..')
flutter_engine_path = File.join(flutter_root, 'bin', 'cache', 'artifacts', 'engine', 'ios')

load File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')

target 'Runner' do
  use_frameworks!

  # Pods para el proyecto Flutter
  pod 'speech_to_text', :path => File.join(flutter_application_path, '.symlinks', 'plugins', 'speech_to_text', 'ios')
  pod 'file_picker', :path => File.join(flutter_application_path, '.symlinks', 'plugins', 'file_picker', 'ios')
  pod 'image_picker', :path => File.join(flutter_application_path, '.symlinks', 'plugins', 'image_picker_ios', 'ios')
  pod 'path_provider_ios', :path => File.join(flutter_application_path, '.symlinks', 'plugins', 'path_provider_ios', 'ios')
  pod 'open_filex', :path => File.join(flutter_application_path, '.symlinks', 'plugins', 'open_filex', 'ios')
  pod 'url_launcher_ios', :path => File.join(flutter_application_path, '.symlinks', 'plugins', 'url_launcher_ios', 'ios')

  install_all_flutter_pods(flutter_application_path)
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
